#lang racket

(define total-unique-instructions 883)
(define total-instructions-with-duplicates 883)

(define per-extension-instruction-count
  (make-immutable-hash
    '(
      (rv32_c . 1)
      (rv32_c_f . 4)
      (rv32_d_zfa . 2)
      (rv32_i . 0)
      (rv32_zbb . 0)
      (rv32_zbkb . 3)
      (rv32_zbs . 0)
      (rv32_zclsd . 0)
      (rv32_zicntr . 0)
      (rv32_zilsd . 0)
      (rv32_zk . 0)
      (rv32_zkn . 0)
      (rv32_zknd . 2)
      (rv32_zkne . 2)
      (rv32_zknh . 6)
      (rv32_zks . 0)
      (rv64_a . 11)
      (rv64_c . 10)
      (rv64_d . 6)
      (rv64_f . 4)
      (rv64_h . 3)
      (rv64_i . 15)
      (rv64_m . 5)
      (rv64_q . 4)
      (rv64_q_zfa . 2)
      (rv64_zacas . 1)
      (rv64_zba . 5)
      (rv64_zbb . 8)
      (rv64_zbkb . 1)
      (rv64_zbs . 4)
      (rv64_zcb . 1)
      (rv64_zfh . 4)
      (rv64_zk . 0)
      (rv64_zkn . 0)
      (rv64_zknd . 5)
      (rv64_zkne . 2)
      (rv64_zknh . 4)
      (rv64_zks . 0)
      (rv_a . 11)
      (rv_c . 23)
      (rv_c_d . 4)
      (rv_c_zicfiss . 0)
      (rv_c_zihintntl . 0)
      (rv_d . 26)
      (rv_d_zfa . 8)
      (rv_d_zfhmin . 2)
      (rv_f . 26)
      (rv_f_zfa . 7)
      (rv_h . 12)
      (rv_i . 37)
      (rv_m . 8)
      (rv_q . 28)
      (rv_q_zfa . 7)
      (rv_q_zfhmin . 2)
      (rv_s . 2)
      (rv_sdext . 1)
      (rv_smrnmi . 1)
      (rv_ssctr . 1)
      (rv_svinval . 3)
      (rv_svinval_h . 2)
      (rv_system . 2)
      (rv_v . 375)
      (rv_v_aliases . 0)
      (rv_zabha . 18)
      (rv_zabha_zacas . 2)
      (rv_zacas . 2)
      (rv_zawrs . 2)
      (rv_zba . 3)
      (rv_zbb . 15)
      (rv_zbc . 3)
      (rv_zbkb . 3)
      (rv_zbkc . 0)
      (rv_zbkx . 2)
      (rv_zbs . 4)
      (rv_zcb . 11)
      (rv_zcmop . 1)
      (rv_zcmp . 6)
      (rv_zcmt . 1)
      (rv_zfbfmin . 2)
      (rv_zfh . 22)
      (rv_zfh_zfa . 7)
      (rv_zfhmin . 6)
      (rv_zicbo . 4)
      (rv_zicfilp . 0)
      (rv_zicfiss . 2)
      (rv_zicntr . 0)
      (rv_zicond . 2)
      (rv_zicsr . 6)
      (rv_zifencei . 1)
      (rv_zihintntl . 0)
      (rv_zimop . 2)
      (rv_zk . 0)
      (rv_zkn . 0)
      (rv_zknh . 4)
      (rv_zks . 0)
      (rv_zksed . 2)
      (rv_zksh . 2)
      (rv_zvbb . 16)
      (rv_zvbc . 4)
      (rv_zvfbfmin . 2)
      (rv_zvfbfwma . 2)
      (rv_zvkg . 2)
      (rv_zvkn . 0)
      (rv_zvkned . 11)
      (rv_zvknha . 3)
      (rv_zvknhb . 0)
      (rv_zvks . 0)
      (rv_zvksed . 3)
      (rv_zvksh . 2)
    )))

(provide total-unique-instructions
         total-instructions-with-duplicates
         per-extension-instruction-count)

;; ====== Auto-generated stats helper functions ======

(define (get-extension-instruction-count ext-sym)
  (hash-ref per-extension-instruction-count ext-sym #f))

(define (list-all-extensions)
  (sort (hash-keys per-extension-instruction-count) symbol<?))

(define (valid-extension? ext-sym)
  (hash-has-key? per-extension-instruction-count ext-sym))

(provide get-extension-instruction-count
         list-all-extensions
         valid-extension?)
